### PR TITLE
Fix index.js

### PR DESCRIPTION
**Pull request by sandrotonon**
Remove path include duplication

### CODE REVIEW

**Comment by robincsamuel** [comment]
@glur4k Does this fix issue #8 ? In the ghost docs, I see storagePath should be defined in construct like,

`this.storagePath = config.getContentPath('images');`

**Comment by sandrotonon** [comment]
Nope, this merge only removes the duplicated path inclusion.

I'm currently testing your solution for issue #8, but this would be another merge :)
Edit: Unfortunately it doesn't work (see issue).

**Comment by robincsamuel** [comment]
ok, but this path inclusion is added as said in the ghost doc. Was it causing issues? Same is there in the ghost's default local file storage module.

**Comment by sandrotonon** [comment]
Yeah thats right, but you included it twice. Once should be enough. The remaining include is still at line 11.

**Comment by robincsamuel** [comment]
Ah okay! I missed that.  Merging now.

**Pull request merged**
